<!-- page content -->
<div class="container-fluid px-4">          
  <h1 class="mt-2"> <i class="fas fa-truck"></i> Choferes</h1>
  <div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel card">
        <div class="x_title card-header mb-1">
          <i class="fas fa-truck"></i>
          Administrar Choferes
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
          </ul>
        </div>
        <div class="x_content card-body">
          <div class="col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card border-0">
              <div class="card-body">
                <form id="form_chofer">
                  <div class="row mb-2">
                    <div class="col-md-3 offset-md-1">
                      <div class="form-floating mb-md-0">
                        <input class="form-control" id="cho_codigo" type="text" placeholder="Ingrese Codigo Chofer" required="required"/>
                        <label class="control-label" for="cho_codigo">Codigo Chofer<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-7">
                      <div class="form-floating">
                        <input class="form-control" id="cho_nombre" type="text" placeholder="Ingrese Nombre del Chofer" required="required"/>
                        <label for="cho_nombre">Nombre del Chofer<span class="required">*</span></label>
                      </div>
                    </div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-md-4 offset-md-1">
                      <div class="form-floating">
                        <input class="form-control" id="cho_correo" type="email" placeholder="nombre@ejemplo.com" required="required"/>
                        <label for="cho_correo">Correo<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-3">
                      <div class="form-floating">
                        <input class="form-control" id="cho_telefono" type="tel" title="ejemplo +44 8984 1234" placeholder="+44 8984 1234" pattern="^\+((?:9[679]|8[035789]|6[789]|5[90]|42|3[578]|2[1-689])|9[0-58]|8[1246]|6[0-6]|5[1-8]|4[013-9]|3[0-469]|2[70]|7|1)(?:\W*\d){0,13}\d$" required="required"/>
                        <label for="cho_telefono">Telefono<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-3">
                      <div class="form-floating mb-md-0">
                        <select id="cho_estado" class="form-control" style="appearance:auto; padding-left:0.4rem;">
                          <option value=""></option>
                          <option value="AL">Alabama</option>
                          <option value="AK">Alaska</option>
                          <option value="AZ">Arizona</option>
                          <option value="AR">Arkansas</option>
                          <option value="CA">California</option>
                          <option value="CO">Colorado</option>
                          <option value="CT">Connecticut</option>
                          <option value="DE">Delaware</option>
                          <option value="DC">District Of Columbia</option>
                          <option value="FL">Florida</option>
                          <option value="GA">Georgia</option>
                          <option value="HI">Hawaii</option>
                          <option value="ID">Idaho</option>
                          <option value="IL">Illinois</option>
                          <option value="IN">Indiana</option>
                          <option value="IA">Iowa</option>
                          <option value="KS">Kansas</option>
                          <option value="KY">Kentucky</option>
                          <option value="LA">Louisiana</option>
                          <option value="ME">Maine</option>
                          <option value="MD">Maryland</option>
                          <option value="MA">Massachusetts</option>
                          <option value="MI">Michigan</option>
                          <option value="MN">Minnesota</option>
                          <option value="MS">Mississippi</option>
                          <option value="MO">Missouri</option>
                          <option value="MT">Montana</option>
                          <option value="NE">Nebraska</option>
                          <option value="NV">Nevada</option>
                          <option value="NH">New Hampshire</option>
                          <option value="NJ">New Jersey</option>
                          <option value="NM">New Mexico</option>
                          <option value="NY">New York</option>
                          <option value="NC">North Carolina</option>
                          <option value="ND">North Dakota</option>
                          <option value="OH">Ohio</option>
                          <option value="OK">Oklahoma</option>
                          <option value="OR">Oregon</option>
                          <option value="PA">Pennsylvania</option>
                          <option value="RI">Rhode Island</option>
                          <option value="SC">South Carolina</option>
                          <option value="SD">South Dakota</option>
                          <option value="TN">Tennessee</option>
                          <option value="TX">Texas</option>
                          <option value="UT">Utah</option>
                          <option value="VT">Vermont</option>
                          <option value="VA">Virginia</option>
                          <option value="WA">Washington</option>
                          <option value="WV">West Virginia</option>
                          <option value="WI">Wisconsin</option>
                          <option value="WY">Wyoming</option>
                        </select>
                        <label for="cho_estado">Estado de residencia<span class="required">*</span></label>
                      </div>
                    </div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-md-5 offset-md-1">
                      <div class="form-floating mb-md-0">
                        <input class="form-control" id="cho_equipamento" type="text" placeholder="Confirm password" required="required" />
                        <label for="cho_equipamento">Equipamento<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-5">
                      <div class="form-floating mb-md-0">
                        <select id="cho_dispacher" class="form-control" style="appearance:auto;">
                          <option value=""></option>
                          <option value="WA">Dispacher A</option>
                          <option value="WV">Dispacher B</option>
                          <option value="WI">Dispacher C</option>
                          <option value="WY">Dispacher D</option>
                        </select>
                        <label for="cho_dispacher">Dispacher Asociado<span class="required">*</span></label>
                      </div>
                    </div>                    
                  </div>
                  <div class="row mb-2">
                    <div class="col-md-5 offset-md-1">
                      <div class="form-floating mb-md-0">
                        <input class="form-control" id="cho_nro_camion" type="text" placeholder="Numero de camion" required="required"/>
                        <label for="cho_nro_camion">Nro Camion<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-5">
                      <div class="form-floating mb-md-0">
                        <input class="form-control" id="cho_nro_trailer" type="text" placeholder="Numero de Trailer" required="required"/>
                        <label for="cho_nro_trailer">Nro Trailer<span class="required">*</span></label>
                      </div>
                    </div>                    
                  </div>
                  <div class="col-xl-3 col-md-4 offset-md-4 mb-2">
                    <div class="card bg-primary text-white mb-2">
                      <div class="card-body">
                        <center><a id="agregar_chofer" class="small text-white stretched-link" href="#">Agregar chofer</a></center>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="x_panel card mb-4">
    <div class="card-header x_title">
      <i class="far fa-list-alt me-1"></i>
        Listado de Choferes
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        </ul>
    </div>
    <div class="card-body x_content">
      <table id="datatablesSimple" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Estado</th>
            <th>Equipo</th>
            <th title="Dispacher asociado al Chofer">Dispacher</th>
            <th>Condicion</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <?php for ($i=0; $i < count($this->choferes); $i++) {
            if($this->choferes[$i]['cho_status']=='1'){
              $a='<a title="Activar/Desactivar" href="#" data-codigo="'.$this->choferes[$i]["cho_pk"].'" data-id="'.$this->choferes[$i]["cho_codigo"].'" data-status="'.$this->choferes[$i]["cho_status"].'" id="desactivar_chofer" class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i> Desact.</a></td>';
              $this->choferes[$i]['cho_status']='Activo';
            }else{
              $a='<a title="Activar/Desactivar" href="#" data-codigo="'.$this->choferes[$i]["cho_pk"].'" data-id="'.$this->choferes[$i]["cho_codigo"].'" data-status="'.$this->choferes[$i]["cho_status"].'" id="desactivar_chofer" class="btn btn-success btn-xs"><i class="fas fa-trash-alt"></i> Activar</a></td>';
              $this->choferes[$i]['cho_status']='Inactivo';
            }
            ?> 
            <tr>
 
              <td class="ver_chofer" data-id="<?php echo $this->choferes[$i]['cho_codigo'] ?>"><center><?php echo $this->choferes[$i]['cho_nombre'] ?></center></td>
              <td><center><?php echo $this->choferes[$i]['cho_estado'] ?></center></td>
              <td><center><?php echo $this->choferes[$i]['cho_equipamento'] ?></center></td>
              <td><center><?php echo $this->choferes[$i]['id_usuario'] ?></center></td>
              <td><center><?php echo $this->choferes[$i]['cho_status'] ?></center></td>
              <td><a href="#" data-toggle="modal" data-target="#modal_editar_usuario" id='boton_modal_editar' data-id="<?php echo $this->choferes[$i]['cho_codigo'] ?>" class="btn btn-warning btn-xs" data-backdrop="static" data-keyboard="false"><i class="fas fa-pencil-alt"></i> Editar </a>
              <?php echo $a ?>
            </tr>
                        <?php } ?>       
          <tr>
              <td>Tiger Nixon</td>
              <td>Distric of Columbia</td>
              <td>Edinburgh</td>
              <td>61</td>
              <td>2011/04/25</td>
              <td>
                <a href="#" data-toggle="modal" data-target="#modal_editar_usuario" id="boton_modal_editar" class="btn btn-warning btn-xs" data-backdrop="static" data-keyboard="false"><i class="fas fa-pencil-alt"></i> Editar</a>
                <a class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i> Eliminar</a>
              </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>


<div class="modal fade bs-example-modal-xl" id="modal_editar_usuario" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Editar Chofer<br><small></small></h4>
        <button id="cerrar_modal_x"  type="button" class="btn btnx"><span aria-hidden="true">×</span>
        <button id="cerrar_modal_oculto" data-dismiss="modal" type="button" class="close btn btnx" hidden></button>
      </div>
      <div class="modal-body">
        <div class="x_content card-body">
          <div class="col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card border-0">
              <div class="card-body">
                <form id="form_chofer_editar">
                  <div class="row mb-1">
                    <div class="col-md-3 offset-md-1">
                      <div class="form-floating mb-1 mb-md-0">
                        <input type="hidden" id="cho_pk">
                        <input class="form-control" id="cho_codigo_editar" type="text" placeholder="Ingrese Codigo Chofer" required="required"/>
                        <label for="cho_codigo_editar">Codigo Chofer<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-7">
                      <div class="form-floating">
                        <input class="form-control" id="cho_nombre_editar" type="text" placeholder="Ingrese Nombre del Chofer" required="required"/>
                        <label for="cho_nombre_editar">Nombre del Chofer<span class="required">*</span></label>
                      </div>
                    </div>
                  </div>
                  <div class="row mb-1">
                    <div class="col-md-4 offset-md-1">
                      <div class="form-floating mb-1">
                        <input class="form-control" id="cho_correo_editar" type="email" placeholder="nombre@ejemplo.com" required="required"/>
                        <label for="cho_correo_editar">Correo<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-3">
                      <div class="form-floating mb-1">
                        <input class="form-control" id="cho_telefono_editar" type="tel" title="ejemplo +44 8984 1234" placeholder="+44 8984 1234" pattern="^\+((?:9[679]|8[035789]|6[789]|5[90]|42|3[578]|2[1-689])|9[0-58]|8[1246]|6[0-6]|5[1-8]|4[013-9]|3[0-469]|2[70]|7|1)(?:\W*\d){0,13}\d$" required="required"/>
                        <label for="cho_telefono_editar">Telefono<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-3">
                      <div class="form-floating mb-1 mb-md-0">
                        <select id="cho_estado_editar" class="form-control" style="appearance:auto; padding-left: 0.5rem;"required="required">
                          <option value=""></option>
                          <option value="AL">Alabama</option>
                          <option value="AK">Alaska</option>
                          <option value="AZ">Arizona</option>
                          <option value="AR">Arkansas</option>
                          <option value="CA">California</option>
                          <option value="CO">Colorado</option>
                          <option value="CT">Connecticut</option>
                          <option value="DE">Delaware</option>
                          <option value="DC">District Of Columbia</option>
                          <option value="FL">Florida</option>
                          <option value="GA">Georgia</option>
                          <option value="HI">Hawaii</option>
                          <option value="ID">Idaho</option>
                          <option value="IL">Illinois</option>
                          <option value="IN">Indiana</option>
                          <option value="IA">Iowa</option>
                          <option value="KS">Kansas</option>
                          <option value="KY">Kentucky</option>
                          <option value="LA">Louisiana</option>
                          <option value="ME">Maine</option>
                          <option value="MD">Maryland</option>
                          <option value="MA">Massachusetts</option>
                          <option value="MI">Michigan</option>
                          <option value="MN">Minnesota</option>
                          <option value="MS">Mississippi</option>
                          <option value="MO">Missouri</option>
                          <option value="MT">Montana</option>
                          <option value="NE">Nebraska</option>
                          <option value="NV">Nevada</option>
                          <option value="NH">New Hampshire</option>
                          <option value="NJ">New Jersey</option>
                          <option value="NM">New Mexico</option>
                          <option value="NY">New York</option>
                          <option value="NC">North Carolina</option>
                          <option value="ND">North Dakota</option>
                          <option value="OH">Ohio</option>
                          <option value="OK">Oklahoma</option>
                          <option value="OR">Oregon</option>
                          <option value="PA">Pennsylvania</option>
                          <option value="RI">Rhode Island</option>
                          <option value="SC">South Carolina</option>
                          <option value="SD">South Dakota</option>
                          <option value="TN">Tennessee</option>
                          <option value="TX">Texas</option>
                          <option value="UT">Utah</option>
                          <option value="VT">Vermont</option>
                          <option value="VA">Virginia</option>
                          <option value="WA">Washington</option>
                          <option value="WV">West Virginia</option>
                          <option value="WI">Wisconsin</option>
                          <option value="WY">Wyoming</option>
                        </select>
                        <label for="cho_estado_editar">Estado de residencia<span class="required">*</span></label>
                      </div>
                    </div>
                  </div>
                  <div class="row mb-1">
                    <div class="col-md-5 offset-md-1">
                      <div class="form-floating mb-1 mb-md-0">
                        <input class="form-control" id="cho_equipamento_editar" type="text" placeholder="Confirm password" required="required"/>
                        <label for="cho_equipamento_editar">Equipamento<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-5">
                      <div class="form-floating mb-1 mb-md-0">
                        <select id="cho_dispacher_editar" class="form-control" style="appearance:auto;"required="required">
                          <option value=""></option>
                          <option value="WA">Dispacher A</option>
                          <option value="WV">Dispacher B</option>
                          <option value="WI">Dispacher C</option>
                          <option value="WY">Dispacher D</option>
                        </select>
                        <label for="cho_dispacher_editar">Dispacher Asociado<span class="required">*</span></label>
                      </div>
                    </div>                    
                  </div>
                  <div class="row mb-1">
                    <div class="col-md-5 offset-md-1">
                      <div class="form-floating mb-md-0">
                        <input class="form-control" id="cho_nro_camion_editar" type="text" placeholder="Numero de camion" required="required"/>
                        <label for="cho_nro_camion_editar">Nro Camion<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-5">
                      <div class="form-floating mb-md-0">
                        <input class="form-control" id="cho_nro_trailer_editar" type="text" placeholder="Numero de Trailer" required="required"/>
                        <label for="cho_nro_trailer_editar">Nro Trailer<span class="required">*</span></label>
                      </div>
                    </div>                    
                  </div>                  
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary btnModal" id="editar_usuario">Editar</button>
        <button id="cerrar_modal_btn" type="button" class="btn btn-default btnModal">Cerrar</button>
      </div>
    </div>
  </div>
</div>  

