<!-- page content -->
<div class="container-fluid px-4">          
  <h1 class="mt-2"> <i class="fas fa-building"></i> Empresas</h1>
  <div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel card">
        <div class="x_title card-header mb-1">
          <i class="fas fa-building"></i>
          Administrar Empresas
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
          </ul>
        </div>
        <div class="x_content card-body">
          <div class="col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card border-0">
              <div class="card-body">
                <form id="form_empresa">
                  <div class="row mb-2">
                    <div class="col-md-3 offset-md-1">
                      <div class="form-floating mb-md-0">
                        <input class="form-control" id="emp_codigo" type="text" placeholder="Ingrese Codigo Empresa" required="required"/>
                        <label class="control-label" for="emp_codigo">Codigo Empresa<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-7">
                      <div class="form-floating">
                        <input class="form-control" id="emp_nombre" type="text" placeholder="Ingrese Nombre de la Empresa" required="required"/>
                        <label for="emp_nombre">Nombre de la Empresa<span class="required">*</span></label>
                      </div>
                    </div>
                  </div>
                  <div class="col-xl-3 col-md-4 offset-md-4 mb-2">
                    <div class="card bg-primary text-white mb-2">
                      <div class="card-body">
                        <center><a id="agregar_empresa" class="small text-white stretched-link" href="#">Agregar Empresa</a></center>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="x_panel card mb-4">
    <div class="card-header x_title">
      <i class="far fa-list-alt me-1"></i>
        Listado de Empresas
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        </ul>
    </div>
    <div class="card-body x_content">
      <table id="datatablesSimple" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Condicion</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <?php for ($i=0; $i < count($this->empresas); $i++) { 
            if($this->empresas[$i]['emp_status']=='1'){
              $a='<a title="Activar/Desactivar" href="#" data-id="'.$this->empresas[$i]["emp_codigo"].'" data-status="'.$this->empresas[$i]["emp_status"].'" id="desactivar_empresa" class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i> Desact.</a></td>';
              $this->empresas[$i]['emp_status']='Activo';
            }else{
              $a='<a title="Activar/Desactivar" href="#" data-id="'.$this->empresas[$i]["emp_codigo"].'" data-status="'.$this->empresas[$i]["emp_status"].'" id="desactivar_empresa" class="btn btn-success btn-xs"><i class="fas fa-trash-alt"></i> Activar</a></td>';
              $this->empresas[$i]['emp_status']='Inactivo';
            }
            ?> 
            <tr>

              <td><center><?php echo $this->empresas[$i]['emp_codigo'] ?></center></td>
              <td><center><?php echo $this->empresas[$i]['emp_nombre'] ?></center></td>
              <td><center><?php echo $this->empresas[$i]['emp_status'] ?></center></td>
              <td><a href="#" data-toggle="modal" data-target="#modal_editar_usuario" id='boton_modal_editar' data-id="<?php echo $this->empresas[$i]['emp_codigo'] ?>" class="btn btn-warning btn-xs" data-backdrop="static" data-keyboard="false"><i class="fas fa-pencil-alt"></i> Editar </a>
              <?php echo $a ?>
            </tr>
                        <?php } ?>       
        </tbody>
      </table>
    </div>
  </div>
</div>


<div class="modal fade bs-example-modal-xl" id="modal_editar_usuario" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Editar Empresa<br><small></small></h4>
        <button id="cerrar_modal_x"  type="button" class="btn btnx"><span aria-hidden="true">×</span>
        <button id="cerrar_modal_oculto" data-dismiss="modal" type="button" class="close btn btnx" hidden></button>
      </div>
      <div class="modal-body">
        <div class="x_content card-body">
          <div class="col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card border-0">
              <div class="card-body">
                <form id="form_empresa_editar">
                  <div class="row mb-1">
                    <div class="col-md-3 offset-md-1">
                      <div class="form-floating mb-1 mb-md-0">
                        <input type="hidden" id="cho_pk">
                        <input class="form-control" id="emp_codigo_editar" type="text" placeholder="Ingrese Codigo Empresa" required="required"/>
                        <label for="emp_codigo_editar">Codigo Empresa<span class="required">*</span></label>
                      </div>
                    </div>
                    <div class="col-md-7">
                      <div class="form-floating">
                        <input class="form-control" id="emp_nombre_editar" type="text" placeholder="Ingrese Nombre de la Empresa" required="required"/>
                        <label for="emp_nombre_editar">Nombre de la Empresa<span class="required">*</span></label>
                      </div>
                    </div>
                  </div>                 
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary btnModal" id="editar_usuario">Editar</button>
        <button id="cerrar_modal_btn" type="button" class="btn btn-default btnModal">Cerrar</button>
      </div>
    </div>
  </div>
</div>