<body>

     <!-- PRE LOADER -->



     <!-- GRID LINE -->
    <section class="grid">
         <div class="container">
            <div class="row">

              <div class="col-md-2 col-sm-2">
                <div class="grid-line"></div>
              </div>
              <div class="col-md-2 col-sm-2">
                <div class="grid-line"></div>
              </div>
              <div class="col-md-2 col-sm-2">
                <div class="grid-line"></div>
              </div>
              <div class="col-md-2 col-sm-2">
                <div class="grid-line"></div>
              </div>
              <div class="col-md-2 col-sm-2">
                <div class="grid-line"></div>
              </div>

            </div>
         </div>
    </section>


     <!-- HOME -->
     <section id="home">
        <div class="overlay"></div>
          <div class="container" style="background:url('<?php echo BASE_URL; ?>public/img/fondo_previo.jpg')">
               <div class="row">

                    <div class="col-md-12 col-sm-12">
                         <div class="home-info">
                              <h1>We are getting ready <br>to launch new site!</h1>
                              <!-- You can change the date time in init.js file -->
                            
                              <div class="subscribe-form">
                                <form action="" method="get">
                                  <input type="email" name="email" class="form-control" placeholder="Enter your email" required="">
                                  <button type="submit" class="form-control"><i class="fas fa-mail-bulk"></i></button>
                                </form>
                              </div>
                         </div>
                    </div>

               </div>
          </div>
     </section>

</body>