<body class="login">
<div>
  <?php echo $retVal = (isset($this->_error)) ? ' <div class="col-md-6 col-md-offset-3 alert alert-danger" role="alert"> <center>'.$this->_error.' <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </center> </div>' : "" ; ?>  
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">

        <div class="animate form login_form">

          <div class="col-md-12"> <center><img width="100%" height="100%" src="<?php echo BASE_URL; ?>public/img/logo1.png"></center></div>
          <h1 style="font: 400 25px Helvetica,Arial,sans-serif;text-align: center; padding-top: 90px;"> Sistema Gestion de Cargas de Camiones</h1>
          <section class="login_content">

            <form action="<?php echo BASE_URL?>login" method="post" autocomplete="off" class="full-box logInForm">
        <input type="hidden" value="1" name="enviar" /> 

              <h1>Ingreso</h1>
              <div>
                <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Usuario" required="true" />
              </div>
              <div>
                <input type="password" class="form-control" id="clave" name="clave" placeholder="Clave" required="true" />
              </div>
              <div>
                <input type="submit" class="btn btn-success submit" name="Entrar" Value="Acceder">
                <a class="reset_pass" href="<?php echo BASE_URL ?>recuperar">¿Perdiste tu contraseña?</a>
              </div>
              <div class="clearfix"></div>

              <div class="separator">
                <!-- <p class="change_link">New to site?
                  <a href="#signup" class="to_register"> Create Account </a>
                </p> -->

                <div class="clearfix"></div>
                <br />

                <div>
                  
                  <p>©2022 All Rights Reserved. MAL C.A. Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        </div>

        <div id="register" class="animate form registration_form">
          <section class="login_content">
            <form>
              <h1>Create Account</h1>
              <div>
                <input type="text" class="form-control" placeholder="Username" required="" />
              </div>
              <div>
                <input type="email" class="form-control" placeholder="Email" required="" />
              </div>
              <div>
                <input type="password" class="form-control" placeholder="Password" required="" />
              </div>
              <div>
                <a class="btn btn-default submit" href="index.html">Submit</a>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">Already a member ?
                  <a href="#signin" class="to_register"> Log in </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="fa fa-paw"></i>Grupo Farma Del Ecuador </h1>
                  <p>©2021 All Rights Reserved. Grupo Farma Del Ecuador. Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>